include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

APP_NAME = TestDrawing 

TestDrawing_OBJC_FILES =  MyController.m \
	main.m

TestDrawing_MAIN_MODEL_FILE = TestDrawing.gorm

TestDrawing_RESOURCE_FILES = TestDrawing.gorm

include $(GNUSTEP_MAKEFILES)/application.make



