include $(GNUSTEP_MAKEFILES)/common.make

TEST_TOOL_NAME = t_AlertPanelScrolling

ADDITIONAL_CPPFLAGS += -I$(GNUSTEP_MAKEFILES)/TestFramework

t_AlertPanelScrolling_OBJC_FILES = t_AlertPanelScrolling.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make
